"""Write redstone/entity_dims.py, each entity type's hitbox size and whether it blocks block
placement, from a decompile of the server's version.

    python -m scripts.entity_dims <decompiled source root, holding net/minecraft>
"""

import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "redstone" / "entity_dims.py"
ENTITY_DIR = "net/minecraft/world/entity"
TYPES = f"{ENTITY_DIR}/EntityTypes.java"
IDS = f"{ENTITY_DIR}/EntityTypeIds.java"
VERSION = "26.3"

REGISTRATION = re.compile(r"public static final EntityType<([\w.]+)> (\w+) = register\(\s*EntityTypeIds\.(\w+),(.*?)\n   \);",
                          re.DOTALL)
SIZED = re.compile(r"\.sized\(([0-9.]+)F, ([0-9.]+)F\)")
ID = re.compile(r"public static final ResourceKey<EntityType<\?>> (\w+) = create\(\"([a-z0-9_]+)\"\);")
CLASS = re.compile(r"\bclass (\w+)(?:<[^{]*?>)? extends ([\w.]+)")
BLOCKS_BUILDING = re.compile(r"this\.blocksBuilding = (?!false;)")


def parse(root: Path) -> tuple[dict[str, tuple[float, float]], list[str]]:
    """(id -> (width, height) at scale 1, sorted ids whose entities block block placement)."""
    ids = dict(ID.findall((root / IDS).read_text()))
    source = (root / TYPES).read_text()
    registrations = REGISTRATION.findall(source)
    if len(registrations) != source.count("= register("):
        raise ValueError(f"parsed {len(registrations)} of {source.count('= register(')} registrations in {TYPES}")

    parent: dict[str, set[str]] = {}
    blockers = set()
    for path in (root / ENTITY_DIR).rglob("*.java"):
        text = path.read_text()
        for name, base in CLASS.findall(text):
            parent.setdefault(name, set()).add(base.split(".")[-1])
        # ArmorStand sets it to !isMarker(); a marker stand's hitbox is zero-sized anyway.
        if BLOCKS_BUILDING.search(text):
            blockers.add(path.stem)

    def blocks(cls: str) -> bool:
        while cls not in blockers:
            if cls == "Entity":
                return False
            bases = parent.get(cls)
            if not bases or len(bases) > 1:
                raise ValueError(f"cannot resolve the superclass of {cls}: {bases}")
            cls = next(iter(bases))
        return True

    dims, blocking = {}, []
    for cls, const, key, body in registrations:
        if const != key or key not in ids:
            raise ValueError(f"{const} registers under EntityTypeIds.{key}")
        sized = SIZED.findall(body)
        if len(sized) != 1:
            raise ValueError(f"{const}: expected one literal .sized(w, h), found {sized}")
        entity = ids[key]
        dims[entity] = (float(sized[0][0]), float(sized[0][1]))
        if blocks(cls.split(".")[-1]):
            blocking.append(entity)
    return dict(sorted(dims.items())), sorted(blocking)


def render(dims: dict[str, tuple[float, float]], blocking: list[str]) -> str:
    lines = [f'"""Generated by scripts/entity_dims.py from {TYPES} (Minecraft {VERSION} decompile); do not edit.',
             "",
             "ENTITY_DIMS: width and height of each entity type's hitbox at scale 1, as registered by",
             "EntityType.Builder.sized. Some entities change it at run time (slime size, baby mobs, small",
             "or marker armor stands, the scale attribute); hanging entities ignore it.",
             "BLOCKS_BUILDING: types whose class sets Entity.blocksBuilding, so a block can't be placed",
             'where their hitbox overlaps it (EntityGetter.isUnobstructed). A marker armor stand does not.',
             '"""',
             "",
             "ENTITY_DIMS: dict[str, tuple[float, float]] = {"]
    lines += [f'    "{e}": ({w!r}, {h!r}),' for e, (w, h) in dims.items()]
    lines += ["}", "", "BLOCKS_BUILDING: frozenset[str] = frozenset({"]
    lines += [f'    "{e}",' for e in blocking]
    lines += ["})", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    dims, blocking = parse(Path(argv[0]))
    OUT.write_text(render(dims, blocking))
    print(f"{OUT}: {len(dims)} entity types, {len(blocking)} block placement")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
