"""Write library/INDEX.md, a catalogue of every building block's variants with measured
size and delay: python -m scripts.index [--tracked]

--tracked leaves out specs git doesn't track or have staged, as the pre-commit hook does, so
the committed index lists only committed specs."""

import subprocess
import sys
from collections import defaultdict
from pathlib import Path

from redstone import fileformat
from redstone.library import LIBRARY, paths
from redstone.traits import design_blocks, dimensions


def row(spec) -> str:
    w, h, d = dimensions(spec)
    delays = sorted({t["delay"] for t in spec.tests if "delay" in t})
    delay = "/".join(map(str, delays)) if delays else "-"
    first = spec.description.split(". ")[0].rstrip(".")
    return (f"| {spec.name} | {w}x{h}x{d} | {w * h * d} | {len(design_blocks(spec))} | {delay} | "
            f"{', '.join(spec.traits)} | {first} |")


def tracked() -> set[Path]:
    # From the repo root: under a commit hook git passes a GIT_INDEX_FILE relative to it, and
    # ls-files reading a missing index lists nothing rather than failing.
    root = LIBRARY.parent
    out = subprocess.run(["git", "ls-files", "--cached", "--", "library/*.redstone.yaml"], cwd=root,
                         capture_output=True, text=True, check=True).stdout
    return {(root / line).resolve() for line in out.splitlines()}


def main(argv: list[str]) -> None:
    keep = tracked() if "--tracked" in argv else None
    folders = defaultdict(list)
    for p in paths():
        if keep is not None and p.resolve() not in keep:
            continue
        folders[p.parent.name].append(fileformat.load(p))
    out = ["# Library index", "",
           "Generated by `python -m scripts.index`. Size is the bounding box (WxHxD, base and "
           "reserved air included, fixtures not); delay is the exact tested truth-table delay in game ticks.", ""]
    for folder in sorted(folders):
        out += [f"## {folder}", "", "| variant | size | volume | blocks | delay | traits | summary |",
                "|---|---|---|---|---|---|---|"]
        out += [row(s) for s in sorted(folders[folder], key=lambda s: s.name)] + [""]
    (LIBRARY / "INDEX.md").write_text("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1:])
